name: employee_attendance_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  dio: ^5.2.1+1
  awesome_dialog: ^3.1.0
  geolocator: ^9.0.2
  sensors_plus: ^3.0.2
  flutter_background_service: ^3.0.1
  permission_handler: ^10.4.3
  flutter_background_service_android: ^4.0.1
  flutter_background_service_ios: ^3.0.0
  connectivity_plus: ^4.0.2

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

